"""added new model for currency_rates

Revision ID: e831b7d78a57
Revises: 
Create Date: 2021-05-10 21:09:35.517183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e831b7d78a57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER()),
    sa.Column('title', sa.VARCHAR(length=100)),
    sa.Column('date_posted', sa.DATETIME()),
    sa.Column('content', sa.TEXT(length=20)),
    sa.Column('user_id', sa.INTEGER()),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER()),
    sa.Column('username', sa.VARCHAR(length=20)),
    sa.Column('email', sa.VARCHAR(length=120)),
    sa.Column('image_file', sa.VARCHAR(length=20)),
    sa.Column('password', sa.VARCHAR(length=60)),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
